# Generated by Django 6.0 on 2026-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignment_file_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
