# Generated by Django 6.0.3 on 2026-03-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_assignment_document_assignmentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='file',
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assignments.submission')),
            ],
        ),
    ]
