# Generated by Django 6.0 on 2026-02-17 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_enrolled_on_enrollment_joined_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='file',
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.coursematerial')),
            ],
        ),
    ]
