# Generated by Django 6.0 on 2026-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_coursematerial_file_materialfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
