# Generated by Django 6.0.2 on 2026-02-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='submission_time',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='total_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
